### ISSUE TITLE
Sigificant video stuttering in playback, only in Flatpak

### ISSUE THREAD

**Issue by jgoerzen** [flathub/org.kde.digikam#11]
I am running the latest Flatpak digikam, which identifies with version 7.0.0-rc in Flatpak, and in Help->About as 7.0.0 with a build date of Sept. 7, 2020.  (Not sure why 7.0.0 release or 7.1.0 isn't in flatpak).

Anyhow, I have a Pixel 2 XL and a Pixel 4a.  Both can capture 4K video with H.264.  This video plays back fine in my Debian buster system using VLC.  My video card is an nVidia GTX 1070.  I am using the Nouveau open-source nvidia drivers.  When playing on the host system with vlc, vlc comments "Trying to open /usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so".    This also worked fine on the older version of Digikam included in buster.

Since I have upgraded to the digikam flatpak, however, this 4K video cannot play smoothly.  There is significant skipping and jumping in the video playback.

The nouveau_drv_video.so file used by vlc is in the Debian package mesa-va-drivers.

I don't know if a missing nouveau_drv_video.so is the cause of this problem, but it might be a reasonable place to start.

-----
Addendum:

I switched to an Intel video-based system with HEVC decoding acceleration (necessary for 4K H.265 playback).  Outside of Digikam, my system is quite capable of playback of both H.264 and H.265 video at 4K.  Within Digikam, however, the issue as I described above persists.

One of the videos is reported by mplayer like this:

Selected video codec: [ffhevc] vfm: ffmpeg (FFmpeg HEVC / H.265)
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))

So that's not MP3.

This is also a regression from Digikam 5.9.0 in regular Debian.  I don't know if something in the newer version hurt, or if flatpak does; either way, the older Digikam was much better about this.

Also Digikam in AppImage doesn't have this issue for me.

I was directed here by https://bugs.kde.org/show_bug.cgi?id=382582.

Thanks for what you do!

**Comment by Erick555** [comment]
Flatpak by default uses openh264 codec for h264 playback which is nerfed but free of patents. For using internal h64 codec from ffmpeg app needs to opt-in into ffmpeg-full extension. See [example](https://github.com/flathub/org.telegram.desktop/blob/master/org.telegram.desktop.json#L24).

**Comment by Erick555** [comment]
@jgoerzen please install digikam from https://github.com/flathub/org.kde.digikam/pull/12#issuecomment-692631627 then make sure you have ffmpeg-full installed as well: `flatpak install --user org.freedesktop.Platform.ffmpeg-full//20.08`

**Comment by jgoerzen** [comment]
Yes, that fixes it!  For both h.264 and h.265!

**Comment by ElXreno** [comment]
Yeah, also tested this on my laptop with Celeron N3060, and yes, it works!
Thanks @Erick555!
