### ISSUE TITLE
digikam stopped working with update to 7.1.0 

### ISSUE THREAD

**Issue by linuxrider** [flathub/org.kde.digikam#13]
digikam stopped working with update to 7.1.0  with the following message:

`ASSERT failure in KCatalogPrivate::setupGettextEnv: "You need to instantiate a Q*Application before using KCatalog", file src/kcatalog.cpp, line 223`

**Comment by Erick555** [comment]
Works for me

**Comment by tsdgeos** [comment]
I can reproduce the problem. I'll have a look

**Comment by tsdgeos** [comment]
Fixed by #15  Will be ready as an update in a few hours
