### ISSUE TITLE
Please update runtimes

### ISSUE THREAD

**Issue by zWhdmB5T** [flathub/org.kde.digikam#131]
@travier @tsdgeos  
Can you please update for `flathub/org.kde.digikam`:
- all `runtime/org.freedesktop.Platform.*` from 23.08 to 24.08
Very appreciated. Thank you!

**Comment by travier** [comment]
Please don't ping people here.

**Comment by travier** [comment]
And this one is already on the 6.7 runtime.

**Comment by travier** [comment]
This will happen when we'll update the apps to the 6.8 Runtime which is based on 24.08.

**Comment by zWhdmB5T** [comment]
OK!
Thank you!
