### ISSUE TITLE
Fix notifications on KDE Plasma

### ISSUE THREAD

**Issue by cthu1hoo** [flathub/org.kde.digikam#29]
Would it be possible to add the following well-known names, so that Digikam notifications are styled properly on KDE Plasma?

```
flatpak --user override org.kde.digikam --talk-name=org.freedesktop.Notifications
flatpak --user override org.kde.digikam --talk-name=org.kde.StatusNotifierWatcher
```

I'm not sure whether both are required, but it certainly doesn't work without the second one.

Thanks!

**Comment by ElXreno** [comment]
First of all, thank you for reporting this and for providing a fix for the problem!
The fix is available in PR: https://github.com/flathub/org.kde.digikam/pull/30

**Comment by cthu1hoo** [comment]
thanks! much appreciated.
