### ISSUE TITLE
Panorama Tools not Available

### ISSUE THREAD

**Issue by Skoddie** [flathub/org.kde.digikam#34]
I recently installed Linux Mint 20.3 (Una) on an old Laptop (first time Linux user) and I installed Digikam 7.6.0 as Flatpak.
When I try to stitch a panorama, Digikam asks for several binaries. I have hugin installed (through APT) but Digikam cannot find the binaries.
I found that I can give Digikam access to the directory with the binaries (/usr/bin) with Flatseal. When I do that, I can find the binaries from within Digikam (/run/host/usr/bin). But even after selecting the binaries in Digikam, Digikam still says that they are not available.

**Comment by i-need-to-tell-you-something** [comment]
Same problem for accessing `exiftools`. Installed via apt, with the binary under `/usr/bin`. After giving it the `filesystem=host` permission, the Digikam flatpak sees the correct binary (under `/var/run/host/usr/bin`), but does nothing when selecting it in the setup dialog for exiftools.

So this seems to apply to any host system binaries. The issue may be renamed to reflect that.

**Comment by Erick555** [comment]
Flatpak apps don;t use host binaries in general. Everything must be included in flatpak.

**Comment by ElXreno** [comment]
When the build will be available (check #39), please check if this problem is fixed for you.
