### ISSUE TITLE
heif decoding in version 7.7.0 not supported 

### ISSUE THREAD

**Issue by pkrause1980** [flathub/org.kde.digikam#40]
SUMMARY
The decoding of heif files fails in version 7.7.0

STEPS TO REPRODUCE
1. Add the example.heic or example.avif (from the libheif git repository, directory "examples") to the collection.

OBSERVED RESULT
They are recognized but not decoded (no thumbnail is shown, the image preview does not work).

ADDITIONAL INFORMATION
I'd guess libde265 is missing:
A) There is no libde265 module in the json.
B) The latest buildlog states at line 100579: "HEIF decoder, libde265: not found" (and similar at other lines).
C) According to issue #32 it should be added? Note that it adds libheif and a duplicate libx265 but no libde265.
D) The appimage supports decoding of heif files, thus I guess the error is not at libheif itself.

Thanks!

**Comment by ElXreno** [comment]
Thanks for the detailed description of the issue! Currently only HEIF decoding is fixed. Progress can be seen in #41.

**Comment by novomesk** [comment]
For AVIF support, I suggest to build kimageformats with libavif and libaom dependencies.
