### ISSUE TITLE
Assertion failed while scanning for new items

### ISSUE THREAD

**Issue by lordShork** [flathub/org.kde.digikam#57]
Every time I open DigiKam after it loads my collections and starts looking for new items, there is a crash after a few seconds.
I already tried starting it as admin and in compatibility mode, which did not change the situation. I'm using a fresh install of Windows 10 Pro 22H2.

![2023-05-01 11_09_23-Window](https://user-images.githubusercontent.com/123649453/235433133-9c47bf3c-8e05-4de8-8911-c4137833e115.png)

**Comment by tsdgeos** [comment]
This is a Windows error, you can't run flatpak in Windows, so that error doesn't belong here, report it to whoever provided you that windows build
