### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by ElXreno** [flathub/org.kde.digikam#61]
Unfortunately, at the moment I do not have enough time to support this package, and very soon I will have to give up everything for a long time.

Is someone willing to take over maintaining `org.kde.digikam`?

**Comment by tsdgeos** [comment]
There's various of us that have commit rights to all of org.kde.*

**Comment by ElXreno** [comment]
So, what should I do next? Should I request that my write access to this repository be revoked? This may reduce the attack surface while I am away.

**Comment by tsdgeos** [comment]
If you have a particular feeling that your account may be abused that seems like a good idea, otherwise personally I don't think it's really necessary.

**Comment by Justinzobel** [comment]
As long as you have 2FA on your account and a strong password I don't see the need to remove it.
