### ISSUE TITLE
(Digikam Flatpak) Please update included runtimes

### ISSUE THREAD

**Issue by zWhdmB5T** [flathub/org.kde.digikam#71]
Please, update!

Included runtimes are v22.08, should be v23.08.

Thank you!

**Comment by Justinzobel** [comment]
See https://github.com/flathub/org.kde.digikam/pull/70 - help and testing appreciated.

**Comment by zWhdmB5T** [comment]
OH, OK. Thank you.

**Comment by zWhdmB5T** [comment]
That's my question, too. Issue not resolved, yet. Though, I actually 
have seen that there are problems getting it done…

**Comment by Justinzobel** [comment]
Because we're tracking the update in the pull request, no need to track it in multiple locations.
